trackingLabel = Tracking
integrationModeLabel = Klaviyo-JavaScript-Integrationsmodus
integrationModeTooltip = Wählen Sie, ob Klaviyo JavaScript über den Google Tag Manager oder über dieses Plugin eingebunden wird.
integrationModeGtm = Über Google Tag Manager integrieren
integrationModePlugin = Klaviyo JavaScript über dieses Plugin bereitstellen
